// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/memoli/MemoliAdmin.tsx": () => import("../components/mockups/memoli/MemoliAdmin.tsx"),
  "./components/mockups/memoli/MemoliApp.tsx": () => import("../components/mockups/memoli/MemoliApp.tsx"),
  "./components/mockups/memoli/MemoliWebsite.tsx": () => import("../components/mockups/memoli/MemoliWebsite.tsx")
};
